**In this part we take the matrix we created for BL count IR2 and make a matrix with new PIDs**

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import functools

Here we upload the the big diagnosis that we have created previously.

In [2]:
final2=pd.read_csv("final.csv", header=None,index_col=[0])

we make it readable order that we need to have with making the columns in appropriate way.

In [3]:
final=final2.rename(columns=final2.iloc[0]).drop(final2.index[0]).reset_index(drop=True)
final

,PATNO,AGE_AT_VISIT,AFICBERB,ASHKJEW,BASQUE,BIRTHDT,SEX,CHLDBEAR,HANDED,HISPLAT,RAASIAN,RABLACK,RAHAWOPI,RAINDALS,RANOS,RAWHITE,COHORT_DEFINITION
0,3000,69.1,0,0,0,12/1941,0,0,1,0,0,0,0,0,0,1,Healthy Control
1,3001,65.1,0,0,0,01/1946,1,NaN,2,0,0,0,0,0,0,1,Parkinson's Disease
2,3002,67.6,0,0,0,08/1943,0,0,1,0,0,0,0,0,0,1,Parkinson's Disease
3,3003,56.7,0,0,0,07/1954,0,0,1,0,0,0,0,0,0,1,Parkinson's Disease
4,3004,59.4,0,0,0,11/1951,1,NaN,1,0,0,0,0,0,0,1,Healthy Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1926,160252,80.3,0,0,0,05/1942,1,NaN,1,0,0,0,0,0,0,1,Parkinson's Disease
1927,161236,55.6,0,0,0,01/1967,1,NaN,1,0,0,0,0,0,0,1,Parkinson's Disease
1928,162140,68.8,0,0,0,10/1953,1,NaN,1,0,0,0,0,0,0,1,Prodromal
1929,162905,45.2,0,0,0,06/1977,1,NaN,1,0,0,1,0,0,0,0,Healthy Control
1930,162929,84.6,0,0,0,01/1938,1,NaN,1,0,0,0,0,0,0,1,Parkinson's Disease

We read off the raw matrix that we have created previously, they usually contain more patient that we have their diagnosis.

In [4]:
path_data=Path("/scratch/znazari/3ir_quant/final_ir3_quant")

In [5]:
bl_matrix=pd.read_csv(path_data/"bl_matrix_quant_ir3.txt", header=None, low_memory=False)

We resolve some problem that we have encoutered for reading the file

In [6]:
bl_matrix2=bl_matrix.rename(columns=bl_matrix.iloc[0]).drop(bl_matrix.index[0]).reset_index(drop=True)

In [7]:
bl_matrix2['Name']

0         ENSG00000210196.2
1         ENSG00000198727.2
2         ENSG00000210194.1
3         ENSG00000198695.2
4         ENSG00000198786.2
                ...
58289     ENSG00000269588.1
58290    ENSG00000132286.11
58291     ENSG00000075131.9
58292    ENSG00000179532.12
58293    ENSG00000166333.13
Name: Name, Length: 58294, dtype: object

Then we read the list of pateint that we have which is big and their diagnosis is not necessary available in the diagnosis matrix.

In [8]:
path1=Path("/scratch/znazari/PPMI_ver_sep2022/RNA_Seq_data/star_ir3/quant/")

In [9]:
bl_files=pd.read_csv(path1/"bl.txt", header=None )

In [10]:
def function_names(fname):
    tokens=fname.split('.')
    return tokens[1]

Below we will have the list of the patient IDs that are still larger than what is supposed to be.

In [11]:
bl_list=[]
for i in range(len(bl_files)):
    bl_list=bl_list+[function_names(bl_files.iloc[i][0])]

Below we ar going to have all the patients that we have their IDs and diagnosis.

In [12]:
patient_diagonises=final[['PATNO','COHORT_DEFINITION']]
patient_diagonises

       PATNO    COHORT_DEFINITION
0       3000      Healthy Control
1       3001  Parkinson's Disease
2       3002  Parkinson's Disease
3       3003  Parkinson's Disease
4       3004      Healthy Control
...      ...                  ...
1926  160252  Parkinson's Disease
1927  161236  Parkinson's Disease
1928  162140            Prodromal
1929  162905      Healthy Control
1930  162929  Parkinson's Disease

[1931 rows x 2 columns]

In [13]:
big_patients=list(patient_diagonises['PATNO'])
len(big_patients)

1931

Below we are going to check how many of those patients that we initially get from the files of the RNA-seq are actually have their diagnosis in the big list of patients with their diagnosis.

In [14]:
contains=[]
not_contains=[]
for i in bl_list:
    if i in big_patients:
        contains+=[i]
    else:
        not_contains+=[i]

Below we neet to get all the patient IDs which are represented as "string" to be presented as type integer, as it was for the list that we had in the orginal RNA-seq matrices.

In [15]:
r_contains=[int(x) for x in contains]

Below we just extract the list of patients that are in the big original diagnosis matrix.

In [16]:
bl_matrix3=bl_matrix2[r_contains]

Below we need to replace the geneID column that were missing previously.

In [17]:
bl_matrix3.insert(loc=0, column ='Geneid',value = bl_matrix2['Name'])

Finally we write the result into a txt file.

In [18]:
#bl_matrix3.to_csv(path_data/"ordered_bl_matrix_ir3_quant.txt")

In [19]:
#bl_matrix3.to_csv("ordered_bl_matrix_ir3_quant.txt")

There we go:

In [20]:
bl_matrix3

,Geneid,10874.0,12499.0,12593.0,13039.0,13424.0,14281.0,14331.0,14426.0,15761.0,...,59614.0,60002.0,60015.0,60024.0,60036.0,60095.0,60171.0,65002.0,65003.0,85242.0
0,ENSG00000210196.2,44.94280,22.461300,40.108300,70.32260,110.738000,45.303300,24.06470,17.95360,110.04000,...,88.869200,37.441900,18.73380,22.53120,33.80580,11.89200,42.46420,2.803520,27.205100,8.36972
1,ENSG00000198727.2,16.76570,24.408300,10.465500,6.48043,25.550700,16.425800,6.54550,6.21096,8.32654,...,13.659000,12.190100,13.63880,17.35220,19.21870,13.84970,14.01250,1.786080,19.350800,46.44210
2,ENSG00000210194.1,49.02850,0.976577,12.834700,8.34336,10.937000,45.303300,32.08630,78.54690,71.12360,...,13.672200,19.414300,6.24460,93.34360,10.32950,10.90100,6.36963,3.738030,29.925600,4.82869
3,ENSG00000198695.2,16.73980,4.088850,8.949160,4.85000,5.546960,19.206300,1.78741,3.61586,26.69980,...,6.779210,3.205410,2.79496,2.57306,4.02895,2.24539,7.71232,0.632933,3.988950,3.39641
4,ENSG00000198786.2,6.78792,7.141770,3.440580,2.51564,10.745000,6.533590,1.84093,2.19335,4.52408,...,4.604020,3.594240,4.79371,4.93000,7.93930,4.34542,4.16134,0.536815,5.573490,22.19120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58289,ENSG00000269588.1,0.00000,0.000000,0.462788,0.00000,0.070936,0.239138,0.00000,0.00000,0.32992,...,0.134392,0.240012,0.00000,0.00000,0.00000,0.00000,0.00000,0.000000,0.235429,0.00000
58290,ENSG00000132286.11,6.83416,10.144200,11.307100,5.68218,11.236400,6.209930,4.09858,7.33341,4.76135,...,9.878270,6.459800,9.45412,4.73179,9.15446,9.59993,7.44339,3.875190,10.718200,4.61597
58291,ENSG00000075131.9,1.99637,2.924220,3.222170,1.42906,2.253710,2.052750,1.01567,1.61544,1.97108,...,2.051210,2.961250,2.70384,1.52379,2.27139,2.25106,2.36083,1.128160,3.464910,2.17195
58292,ENSG00000179532.12,2.38132,6.721180,7.635380,2.39698,6.980680,3.522930,1.67399,1.73295,1.88467,...,4.434150,3.371850,4.56343,3.28040,6.73499,4.83778,3.13288,0.766779,6.796870,4.41617
58293,ENSG00000166333.13,14.68910,19.820100,16.473000,19.49220,21.817000,13.743300,6.57733,8.85544,8.00895,...,17.805100,11.762800,21.51240,12.28790,13.99380,14.51780,13.41050,6.056570,15.077400,16.06490