In [5]:
!pip3 install xgboost

Collecting xgboost
  Downloading xgboost-1.7.4-py3-none-manylinux2014_x86_64.whl (193.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 MB 5.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy in /home/znazari/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in /home/znazari/anaconda3/lib/python3.9/site-packages (from xgboost) (1.9.1)
Installing collected packages: xgboost
Successfully installed xgboost-1.7.4

In [20]:
from xgboost import XGBClassifier
import numpy as np
import pandas as pd
from pathlib import Path
import functools

In [7]:
# read data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [8]:
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)
# create model instance
bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
# fit model
bst.fit(X_train, y_train)
# make predictions

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [9]:
preds = bst.predict(X_test)

In [19]:
preds

array([1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 0, 2,
       1, 2, 0, 2, 1, 0, 0, 0])

In [15]:
data['data'].shape

(150, 4)

In [16]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [13]:
 data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
 data['target'].shape

(150,)

In [28]:
#loading the data

path1=Path("/home/znazari/machine_learning_ppmi")

data_rna1=pd.read_csv(path1/"ordered_bl_matrix_ir2_count.txt", header=None,index_col=[0] )
data_rna=data_rna1.rename(columns=data_rna1.iloc[0]).drop(data_rna1.index[0]).reset_index(drop=True)

In [30]:
data_predict1=pd.read_csv(path1/"the_diagnosis_count_ir2.txt", header=None ,index_col=[0])
data_predict=data_predict1.rename(columns=data_predict1.iloc[0]).drop(data_predict1.index[0]).reset_index(drop=True)

In [29]:
data_rna

,Geneid,10874,12499,12593,13039,13424,14281,14331,14426,15761,...,59614,60002,60015,60024,60036,60095,60171,65002,65003,85242
0,ENSG00000223972.4,10,10,12,7,10,5,7,4,4,...,3,9,9,8,11,2,1,5,6,6
1,ENSG00000227232.4,192,418,276,252,292,235,162,209,128,...,348,158,205,210,512,211,134,168,235,432
2,ENSG00000243485.2,0,0,2,0,0,0,0,0,0,...,0,2,0,0,1,1,0,0,0,0
3,ENSG00000237613.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020.2,1,0,0,0,0,1,0,0,1,...,2,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57815,ENSG00000198695.2,346,142,169,158,138,241,65,83,493,...,258,136,69,86,132,59,142,50,93,92
57816,ENSG00000210194.1,48,17,28,24,24,54,3,7,85,...,46,25,10,16,13,12,13,5,16,4
57817,ENSG00000198727.2,766,1506,405,379,1316,581,501,328,517,...,966,461,498,1049,1260,494,402,147,872,2501
57818,ENSG00000210195.2,62,54,16,67,130,60,63,72,62,...,74,25,48,56,73,34,54,117,27,26
57819,ENSG00000210196.2,169,133,65,221,275,95,178,174,198,...,289,87,89,204,212,68,103,159,94,62

In [32]:
data_rna_=data_rna.drop(columns='Geneid')

In [40]:
data_rna_1=data_rna_.T
data_rna_1

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
10874,10,192,0,0,1,3,0,38,0,3,...,976,2,1,8,511,346,48,766,62,169
12499,10,418,0,0,0,0,0,67,0,0,...,1577,0,0,0,763,142,17,1506,54,133
12593,12,276,2,0,0,4,3,93,0,10,...,379,0,0,1,234,169,28,405,16,65
13039,7,252,0,0,0,1,0,33,0,2,...,440,2,0,1,222,158,24,379,67,221
13424,10,292,0,0,0,0,0,54,0,2,...,1508,0,1,2,1007,138,24,1316,130,275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60095,2,211,1,0,0,0,0,57,0,0,...,480,0,1,0,275,59,12,494,34,68
60171,1,134,0,0,0,0,0,6,0,0,...,474,0,0,1,217,142,13,402,54,103
65002,5,168,0,0,0,0,0,20,0,0,...,134,0,0,0,86,50,5,147,117,159
65003,6,235,0,0,0,2,1,71,0,4,...,980,0,0,0,442,93,16,872,27,94
85242,6,432,0,0,0,0,0,141,0,0,...,2173,0,3,1,1838,92,4,2501,26,62

In [37]:
data_predict_=data_predict['COHORT_DEFINITION']
data_predict_

0       Parkinson's Disease
1           Healthy Control
2       Parkinson's Disease
3       Parkinson's Disease
4       Parkinson's Disease
               ...
1123              Prodromal
1124    Parkinson's Disease
1125              Prodromal
1126              Prodromal
1127    Parkinson's Disease
Name: COHORT_DEFINITION, Length: 1128, dtype: object

In [51]:
data_predict['COHORT_DEFINITION'].replace(['Healthy Control', 'Prodromal','SWEDD',"Parkinson's Disease"],
                        [0, 1,2,3], inplace=True)

In [54]:
data1_pred=data_predict['COHORT_DEFINITION']
data1_pred

0       3
1       0
2       3
3       3
4       3
       ..
1123    1
1124    3
1125    1
1126    1
1127    3
Name: COHORT_DEFINITION, Length: 1128, dtype: int64

In [61]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(data_rna_1,data1_pred, test_size=.3)

In [62]:
bst1 = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='reg:logistic')

In [63]:
bst1.fit(X_train1, y_train1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [64]:
preds1 = bst1.predict(X_test1)

In [65]:
preds1

array([3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3,
       3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3,
       0, 3, 0, 1, 3, 3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       1, 3, 3, 3, 3, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 0, 3, 1, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, 0,
       3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 1, 3, 1, 3, 1, 0, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 0, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 0,
       3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
       3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
       3, 1, 3, 3, 3, 1, 3, 3, 3])

In [66]:
X_test1

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
3958,10,139,8,0,0,6,3,49,0,30,...,528,5,0,4,513,992,157,528,35,175
3226,6,321,0,0,0,0,0,70,0,1,...,656,0,0,0,301,164,8,600,97,128
42443,12,263,0,0,0,0,0,37,0,0,...,1109,0,0,0,509,90,15,933,27,167
3029,9,236,0,0,0,0,0,61,0,0,...,612,0,0,0,291,68,6,520,71,92
3630,1,196,0,0,0,0,0,107,0,0,...,618,0,0,0,322,83,13,619,50,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,4,185,0,0,0,0,0,42,0,0,...,544,0,1,0,337,89,6,577,56,104
55577,1,148,0,0,0,0,0,40,0,1,...,996,0,0,0,403,82,9,595,51,102
40730,2,183,0,0,0,0,0,48,0,0,...,921,0,0,0,557,105,15,551,179,162
42128,1,132,0,0,0,0,0,3,0,0,...,348,0,0,0,197,39,3,349,23,79
3281,14,136,3,0,5,3,0,21,0,31,...,289,4,0,1,227,311,40,239,18,104