**In this part we take the matrix we created for BL count IR2 and make a matrix with new PIDs**

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import functools

Here we upload the the big diagnosis that we have created previously.

In [2]:
final2=pd.read_csv("final.csv", header=None,index_col=[0])

#we make it readable order that we need to have with making the columns in appropriate way.

final1=final2.rename(columns=final2.iloc[0]).drop(final2.index[0]).reset_index(drop=True)
final1

In [4]:
path_data=Path("/scratch/znazari/matrix_generation/new_jobs_counts_ir2/final_data_count/")

We read off the raw matrix that we have created previously, they usually contain more patient that we have their diagnosis.

In [5]:
bl_matrix=pd.read_csv(path_data/"bl_matrix_counts_ir2.txt", header=None, low_memory=False)

We resolve some problem that we have encoutered for reading the file

In [6]:
bl_matrix2=bl_matrix.rename(columns=bl_matrix.iloc[0]).drop(bl_matrix.index[0]).reset_index(drop=True)

In [7]:
bl_matrix2['Geneid']

0        ENSG00000223972.4
1        ENSG00000227232.4
2        ENSG00000243485.2
3        ENSG00000237613.2
4        ENSG00000268020.2
               ...
57815    ENSG00000198695.2
57816    ENSG00000210194.1
57817    ENSG00000198727.2
57818    ENSG00000210195.2
57819    ENSG00000210196.2
Name: Geneid, Length: 57820, dtype: object

Then we read the list of pateint that we have which is big and their diagnosis is not necessary available in the diagnosis matrix.

In [8]:
path1=Path("/scratch/znazari/PPMI_ver_sep2022/RNA_Seq_data/star_ir2/counts/")

In [9]:
bl_files=pd.read_csv(path1/"bl.txt", header=None )

In [10]:
def function_names(fname):
    tokens=fname.split('.')
    return tokens[1]

Below we will have the list of the patient IDs that are still larger than what is supposed to be.

In [11]:
bl_list=[]
for i in range(len(bl_files)):
    bl_list=bl_list+[function_names(bl_files.iloc[i][0])]

Below we ar going to have all the patients that we have their IDs and diagnosis.

In [12]:
patient_diagonises=final1[['PATNO','COHORT_DEFINITION']]
patient_diagonises

       PATNO    COHORT_DEFINITION
0       3000      Healthy Control
1       3001  Parkinson's Disease
2       3002  Parkinson's Disease
3       3003  Parkinson's Disease
4       3004      Healthy Control
...      ...                  ...
1207  160252  Parkinson's Disease
1208  161236  Parkinson's Disease
1209  162140            Prodromal
1210  162905      Healthy Control
1211  162929  Parkinson's Disease

[1212 rows x 2 columns]

In [13]:
big_patients=list(patient_diagonises['PATNO'])
len(big_patients)

1212

Below we are going to check how many of those patients that we initially get from the files of the RNA-seq are actually have their diagnosis in the big list of patients with their diagnosis.

In [14]:
contains=[]
not_contains=[]
for i in bl_list:
    if i in big_patients:
        contains+=[i]
    else:
        not_contains+=[i]

Below we neet to get all the patient IDs which are represented as "string" to be presented as type integer, as it was for the list that we had in the orginal RNA-seq matrices.

In [15]:
r_contains=[int(x) for x in contains]

Below we just extract the list of patients that are in the big original diagnosis matrix.

In [16]:
bl_matrix3=bl_matrix2[r_contains]

Below we need to replace the geneID column that were missing previously.

In [17]:
bl_matrix3.insert(loc=0, column ='Geneid',value = bl_matrix2['Geneid'])

In [18]:
bl_matrix3.head(20)

,Geneid,10874,12499,12593,13039,13424,14281,14331,14426,15761,...,4136,41381,4139,60002,60015,60024,60036,60095,60171,85242
0,ENSG00000223972.4,10,10,12,7,10,5,7,4,4,...,23,7,4,9,9,8,11,2,1,6
1,ENSG00000227232.4,192,418,276,252,292,235,162,209,128,...,273,260,216,158,205,210,512,211,134,432
2,ENSG00000243485.2,0,0,2,0,0,0,0,0,0,...,0,0,1,2,0,0,1,1,0,0
3,ENSG00000237613.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020.2,1,0,0,0,0,1,0,0,1,...,4,1,0,0,0,0,0,0,0,0
5,ENSG00000240361.1,3,0,4,1,0,1,0,0,4,...,1,0,0,1,0,0,0,0,0,0
6,ENSG00000186092.4,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ENSG00000238009.2,38,67,93,33,54,33,43,47,16,...,97,39,32,113,61,131,102,57,6,141
8,ENSG00000239945.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,ENSG00000233750.3,3,0,10,2,2,6,1,1,8,...,12,1,0,2,4,0,3,0,0,0
10,ENSG00000237683.5,28,82,38,31,125,155,44,38,25,...,363,70,50,65,80,210,307,43,12,1171
11,ENSG00000268903.1,0,2,2,3,0,1,3,0,3,...,3,2,0,4,5,1,4,0,2,257
12,ENSG00000269981.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,ENSG00000239906.1,5,26,13,16,15,23,4,1,4,...,35,8,3,3,12,11,27,5,3,29
14,ENSG00000241860.2,114,277,183,131,252,139,96,156,127,...,295,92,61,198,234,304,308,144,38,401
15,ENSG00000222623.1,8,53,29,14,48,4,20,17,9,...,14,9,6,39,34,50,15,16,4,10
16,ENSG00000241599.1,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,ENSG00000228463.4,38,176,178,157,130,50,55,76,106,...,178,32,89,114,159,176,143,213,25,192
18,ENSG00000241670.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,ENSG00000237094.7,1,7,2,1,6,2,6,2,6,...,17,4,1,11,3,9,7,3,0,3

In [19]:
len(bl_matrix3)

57820

In [20]:
def f_names(fname):
    tokens=fname.split('.')
    return tokens[0]

In [21]:
%%time
#enhanced =D
for i in range(len(bl_matrix3)):
    x_x=bl_matrix3.loc[i,"Geneid"]
    j_j=x_x.split('.')
    y_y=j_j[0]
    bl_matrix3.loc[i, 'Geneid']=y_y
bl_matrix3

CPU times: user 6.79 s, sys: 975 Âµs, total: 6.79 s
Wall time: 6.79 s

,Geneid,10874,12499,12593,13039,13424,14281,14331,14426,15761,...,4136,41381,4139,60002,60015,60024,60036,60095,60171,85242
0,ENSG00000223972,10,10,12,7,10,5,7,4,4,...,23,7,4,9,9,8,11,2,1,6
1,ENSG00000227232,192,418,276,252,292,235,162,209,128,...,273,260,216,158,205,210,512,211,134,432
2,ENSG00000243485,0,0,2,0,0,0,0,0,0,...,0,0,1,2,0,0,1,1,0,0
3,ENSG00000237613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020,1,0,0,0,0,1,0,0,1,...,4,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57815,ENSG00000198695,346,142,169,158,138,241,65,83,493,...,236,205,102,136,69,86,132,59,142,92
57816,ENSG00000210194,48,17,28,24,24,54,3,7,85,...,33,29,9,25,10,16,13,12,13,4
57817,ENSG00000198727,766,1506,405,379,1316,581,501,328,517,...,1026,583,339,461,498,1049,1260,494,402,2501
57818,ENSG00000210195,62,54,16,67,130,60,63,72,62,...,64,11,45,25,48,56,73,34,54,26
57819,ENSG00000210196,169,133,65,221,275,95,178,174,198,...,144,31,114,87,89,204,212,68,103,62

#  filter the data with only choosing the protein coding+IncRNA genes 
Ivan Arisi kindly sent the file

In [23]:
path_i=Path("/home/znazari/ppmi_files/")

protein_ivan=pd.read_csv(path_i/"HUGO_protein_coding_genes_plus_high_confidence_lncRNA.txt",sep='\t', header=None)
protein_ivan.columns = ["Ensembl gene ID"]
protein_ivan

       Ensembl gene ID
0      ENSG00000233008
1      ENSG00000249447
2      ENSG00000229702
3      ENSG00000250107
4      ENSG00000231789
...                ...
35280  ENSG00000203995
35281  ENSG00000162378
35282  ENSG00000159840
35283  ENSG00000074755
35284  ENSG00000036549

[35285 rows x 1 columns]

list(protein_ivan.loc[:,'Ensembl gene ID'])

%%time
bb_=bl_matrix3.copy()
for i in range(4, 14):
    bb_.drop(i, inplace=True)

# using drop function is super slow.

%%time
indices=[]
cb_=bl_matrix3.copy()
for i in range(4, 14):
    indices+=[i]
indices    
df1 = cb_[~cb_.index.isin(indices)].copy()
df1
# istead the above piece of code is way better.

%%time
container=[]
cpy_bl=bl_matrix3.copy()
for i in range(len(cpy_bl)):
    if cpy_bl.loc[i,"Geneid"] in list(protein_ivan.loc[:,'Ensembl gene ID']):
        container += [cpy_bl.loc[i,"Geneid"]]
        cpy_bl.drop(i, inplace=True)
        
       
len(container)

Below we try to find the indices of the genes that are actually in the protein coding genes file
we also get the container which contains those geneIDs < this is not necessary though.

In [24]:
%%time
container=[]
cpy_bl=bl_matrix3.copy()
lis_=[]
for i in range(len(cpy_bl)):
    if cpy_bl.loc[i,"Geneid"] in list(protein_ivan.loc[:,'Ensembl gene ID']):
        lis_+=[i]
        container += [cpy_bl.loc[i,"Geneid"]]        
       
len(container)

CPU times: user 2min 44s, sys: 423 ms, total: 2min 44s
Wall time: 2min 44s

29558

In [25]:
# we then try to figute out what indices of the genes IDs need to be dropped by subtracting the lists
large_lis=list(range(0,57820))
res=list(set(large_lis)-set(lis_))
res;

In [26]:
# here we check if it did it correctly:
len(large_lis)-len(res)

29558

Below we drop the gene IDs based on their indices that we figuered out previously and it is SUPER FAST.

In [27]:
%%time
df_matrix3 = cpy_bl[~cpy_bl.index.isin(res)].copy()

CPU times: user 231 ms, sys: 400 ms, total: 631 ms
Wall time: 622 ms

In [28]:
b_df_matrix3=df_matrix3.copy()
b_df_matrix3.reset_index(drop=True, inplace=True)
b_df_matrix3

,Geneid,10874,12499,12593,13039,13424,14281,14331,14426,15761,...,4136,41381,4139,60002,60015,60024,60036,60095,60171,85242
0,ENSG00000243485,0,0,2,0,0,0,0,0,0,...,0,0,1,2,0,0,1,1,0,0
1,ENSG00000237613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000186092,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000238009,38,67,93,33,54,33,43,47,16,...,97,39,32,113,61,131,102,57,6,141
4,ENSG00000239945,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29553,ENSG00000212907,385,369,60,138,460,138,173,144,151,...,379,257,102,148,176,305,507,115,140,881
29554,ENSG00000198886,976,1577,379,440,1508,627,534,406,603,...,1403,652,333,546,669,1231,1727,480,474,2173
29555,ENSG00000198786,511,763,234,222,1007,429,203,186,428,...,689,479,230,237,311,525,848,275,217,1838
29556,ENSG00000198695,346,142,169,158,138,241,65,83,493,...,236,205,102,136,69,86,132,59,142,92
29557,ENSG00000198727,766,1506,405,379,1316,581,501,328,517,...,1026,583,339,461,498,1049,1260,494,402,2501

Finally we write the result into a txt file.

In [28]:
path_data=Path("/scratch/znazari/matrix_generation/new_jobs_counts_ir2/final_data_count/")

In [29]:
b_df_matrix3.to_csv(path_data/"p_ordered_bl_matrix_ir2_count.txt")

In [30]:
ml_path=Path("/home/znazari/machine_learning_ppmi")
b_df_matrix3.to_csv(ml_path/"p_ordered_bl_matrix_ir2_count.txt")