In [1]:
# In case you do not have following packages installed, uncomment instalisation.

import pandas as pd
import numpy as np
import os
import glob
import functools
from pathlib import Path
import matplotlib.pyplot as plt

#!pip install dask[complete];
# you need to run these in case dask gives you error, it might need update.
#!pip install --upgrade pandas "dask[complete]"
#python -m pip install "dask[dataframe]" --upgrade
#import dask.dataframe as dd

from sklearn.model_selection import train_test_split

from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, accuracy_score
from sklearn.metrics import roc_auc_score, confusion_matrix, precision_recall_curve

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import StratifiedKFold
from sklearn.inspection import permutation_importance       

from sklearn.feature_selection import SelectFromModel
from sklearn.utils import class_weight

#!pip3 install xgboost
#from xgboost import XGBClassifier

#!pip install conorm
#import conorm # for tmm normalisation

#!pip3 install pydeseq2 or pip install pydeseq2
#from pydeseq2.dds import DeseqDataSet
#from pydeseq2.ds import DeseqStats
#from pydeseq2.utils import load_example_data



#to install R :
#conda install -c r r-irkernel

#to install a library from R
#!pip install library edgeR
# pip install rpy2

### Data for Parkinson ###

In [2]:
path2 = Path("/home/znazari/data")# where the output data will be saved at the end. 
path3 = Path("/home/znazari/data/open_proteomic/")

In [4]:
proteomic_annotation = pd.read_csv(path3/"PPMI_Project_151_pqtl_Analysis_Annotations_20210210.csv",delimiter=',')
proteomic_annotation;

In [5]:
proteomic = pd.read_csv(path3/"Project_151_pQTL_in_CSF_1_of_7_Batch_Corrected_.csv",delimiter=',')
proteomic

,PATNO,SEX,COHORT,CLINICAL_EVENT,TYPE,TESTNAME,TESTVALUE,UNITS,PLATEID,RUNDATE,PROJECTID,PI_NAME,PI_INSTITUTION,update_stamp
0,53595,Female,PD,BL,Cerebrospinal Fluid,5632-6_3,10.182013,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:41.0
1,53595,Female,PD,BL,Cerebrospinal Fluid,5631-83_3,6.346285,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:41.0
2,53595,Female,PD,BL,Cerebrospinal Fluid,5630-48_3,12.943830,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:41.0
3,53595,Female,PD,BL,Cerebrospinal Fluid,5629-58_3,5.891402,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:41.0
4,53595,Female,PD,BL,Cerebrospinal Fluid,5628-21_3,12.836350,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803875,3825,Male,PD,BL,Cerebrospinal Fluid,12908-15_3,6.522282,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:08.0
803876,3825,Male,PD,BL,Cerebrospinal Fluid,12906-137_3,6.020084,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:08.0
803877,3825,Male,PD,BL,Cerebrospinal Fluid,12904-180_3,4.182774,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:08.0
803878,3825,Male,PD,BL,Cerebrospinal Fluid,12900-29_3,7.283812,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:08.0
803879,3825,Male,PD,BL,Cerebrospinal Fluid,12898-5_3,3.335224,log2 RFU,P0022899,2019-08-04,151,David Stone,Merck,2022-05-13 10:38:08.0

In [29]:
# Specify the base file name and path
base_file_name = "Project_151_pQTL_in_CSF_{}_of_7_Batch_Corrected_.csv"

# Number of files
num_files = 7

# List to store DataFrames
dfs = []

# Loop through the file indices and read each file
for file_index in range(1, num_files + 1):
    file_name = base_file_name.format(file_index)
    file_path = path3 / file_name
    
    # Check if the file exists before attempting to read it
    if file_path.is_file():
        # Read the CSV file and append it to the list
        df = pd.read_csv(file_path, delimiter=',')
        dfs.append(df)
    else:
        print(f"File {file_name} not found.")

In [27]:
dfs[6]

,PATNO,SEX,COHORT,CLINICAL_EVENT,TYPE,TESTNAME,TESTVALUE,UNITS,PLATEID,RUNDATE,PROJECTID,PI_NAME,PI_INSTITUTION,update_stamp
0,59649,Male,PD,BL,Cerebrospinal Fluid,5632-6_3,11.026966,log2 RFU,P0024868,2019-02-12,151,David Stone,Merck,2022-05-13 10:38:41.0
1,59649,Male,PD,BL,Cerebrospinal Fluid,5631-83_3,6.609041,log2 RFU,P0024868,2019-02-12,151,David Stone,Merck,2022-05-13 10:38:41.0
2,59649,Male,PD,BL,Cerebrospinal Fluid,5630-48_3,13.466670,log2 RFU,P0024868,2019-02-12,151,David Stone,Merck,2022-05-13 10:38:41.0
3,59649,Male,PD,BL,Cerebrospinal Fluid,5629-58_3,5.835645,log2 RFU,P0024868,2019-02-12,151,David Stone,Merck,2022-05-13 10:38:41.0
4,59649,Male,PD,BL,Cerebrospinal Fluid,5628-21_3,12.769220,log2 RFU,P0024868,2019-02-12,151,David Stone,Merck,2022-05-13 10:38:41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722530,3917,Male,Control,BL,Cerebrospinal Fluid,9745-20_3,6.931300,log2 RFU,P0024869,2019-02-12,151,David Stone,Merck,2022-05-13 10:39:16.0
722531,3917,Male,Control,BL,Cerebrospinal Fluid,9747-48_3,7.043459,log2 RFU,P0024869,2019-02-12,151,David Stone,Merck,2022-05-13 10:39:16.0
722532,3917,Male,Control,BL,Cerebrospinal Fluid,9748-31_3,8.461362,log2 RFU,P0024869,2019-02-12,151,David Stone,Merck,2022-05-13 10:39:16.0
722533,3917,Male,Control,BL,Cerebrospinal Fluid,9749-190_3,9.049630,log2 RFU,P0024869,2019-02-12,151,David Stone,Merck,2022-05-13 10:39:16.0
722534,3917,Male,Control,BL,Cerebrospinal Fluid,9750-7_3,6.160818,log2 RFU,P0024869,2019-02-12,151,David Stone,Merck,2022-05-13 10:39:16.0

In [41]:
# Concatenate all DataFrames into a single DataFrame
result_df = pd.concat(dfs, ignore_index=True)

# Filter out patients diagnosed as Prodromal
result_df = result_df[result_df['COHORT'] != 'Prodromal']

# Pivot the DataFrame to get the desired format
result_pivot = result_df.pivot(index='TESTNAME', columns='PATNO', values='TESTVALUE')

In [42]:
result_pivot

PATNO,3000,3001,3002,3003,3004,3006,3007,3008,3009,3010,...,74067,74199,74817,75409,75421,75480,75484,75505,75524,75562
TESTNAME,,,,,,,,,,,,,,,,,,,,,
10000-28_3,7.016730,7.454336,7.247439,7.010630,6.877898,6.842311,7.754820,7.001725,6.820676,7.104007,...,6.899428,6.816018,6.853592,6.781720,6.924048,6.758358,6.870476,6.844687,7.029326,6.666132
10001-7_3,7.870548,8.121843,8.344479,7.222104,7.650171,7.092575,7.806605,8.196070,7.769967,7.359637,...,7.997572,7.275574,7.427730,7.834432,8.015048,7.337290,7.599946,7.499072,7.612910,7.258944
10003-15_3,6.147252,6.222071,6.065235,6.138153,6.203758,6.221370,6.174415,6.171208,6.280763,6.188014,...,6.324074,6.192135,6.248550,6.312524,6.219102,6.054284,6.384542,6.236579,6.343984,6.186476
10006-25_3,6.371610,6.418159,6.365775,6.357083,6.361865,6.183732,6.238306,6.332403,6.393692,6.567999,...,6.303177,6.577943,6.329391,6.163935,6.480985,6.350333,6.355463,6.292218,6.339972,6.344696
10008-43_3,5.882283,5.934242,5.827745,5.914232,5.893985,6.054652,5.939613,6.070155,5.952001,5.913274,...,5.988861,5.892367,5.974385,5.883404,5.922584,6.049692,5.950037,5.970764,5.944815,5.865619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993-11_3,6.230929,6.209682,6.586607,6.225973,6.257445,6.412115,7.233072,5.979002,6.252459,6.274228,...,6.218115,6.537651,6.495690,6.300791,6.372259,6.215987,6.386449,6.247486,6.541717,6.430384
9994-217_3,7.031689,7.129638,7.345001,7.330257,7.413496,7.024051,6.918511,6.947370,7.070061,7.149448,...,7.076340,7.068358,7.308743,7.017250,6.983826,7.071633,7.193699,7.390031,7.071616,7.576549
9995-6_3,9.630040,9.827683,9.805028,8.835570,9.094281,8.520557,9.484474,9.514471,9.189601,9.000802,...,9.627819,9.281438,9.397977,9.215428,9.766957,8.772783,9.377158,9.155109,9.443181,9.159902
9997-12_3,8.877616,9.030835,9.008732,8.130329,8.383184,8.005259,8.451975,8.959583,8.465400,8.140073,...,8.949628,9.365799,8.922421,8.668804,9.387384,8.370231,8.946538,8.796960,8.653570,9.174790
9999-1_3,9.215616,9.513951,9.255754,8.858118,9.156273,8.622377,9.286008,9.316983,8.912504,9.192102,...,9.294467,9.008728,9.291964,8.923594,9.695732,8.762823,9.578116,9.112629,9.096812,9.008768

In [43]:
patient_diagnosis_df = result_df[['PATNO', 'COHORT']].drop_duplicates()

In [44]:
patient_diagnosis_df

         PATNO   COHORT
0        53595       PD
4785      3029  Control
9570      3963       PD
14355     3316  Control
19140     3124       PD
...        ...      ...
5512320   3812  Control
5517105   3817  Control
5521890   3792       PD
5526675   3793       PD
5536245   3917  Control

[803 rows x 2 columns]

In [46]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

# Assuming you have two DataFrames: result_pivot and patient_diagnosis_df

#  Merge the two DataFrames on 'PATNO'
merged_df = pd.merge(result_pivot.T, patient_diagnosis_df, on='PATNO')

# Separate features (X) and target variable (y)
X = merged_df.drop(['PATNO', 'COHORT'], axis=1)
y = merged_df['COHORT']

# Convert diagnosis labels to numeric values using LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42)

#  Initialize and train the XGBoost model
xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)

#  Make predictions on the testing set
y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]

# Calculate AU-ROC score
au_roc_score = roc_auc_score(y_test, y_pred_proba)

# Print the AU-ROC score
print(f'AU-ROC Score: {au_roc_score}')

AU-ROC Score: 0.8103748910200523

In [48]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score



# Merge the two DataFrames on 'PATNO'
merged_df = pd.merge(result_pivot.T, patient_diagnosis_df, on='PATNO')

# Separate features (X) and target variable (y)
X = merged_df.drop(['PATNO', 'COHORT'], axis=1)
y = merged_df['COHORT']

# Convert diagnosis labels to numeric values using LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Initialize StratifiedKFold for cross-validation
n_splits = 10  # Number of folds
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize an array to store AU-ROC scores
au_roc_scores = []

# Perform cross-validation and repeat XGBoost algorithm
for _ in range(5):  # Repeat 5 times
    for train_index, test_index in skf.split(X, y_encoded):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y_encoded[train_index], y_encoded[test_index]

        # Initialize and train the XGBoost model
        xgb_model = XGBClassifier()
        xgb_model.fit(X_train, y_train)

        # Make predictions on the testing set
        y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]

        # Calculate AU-ROC score
        au_roc_score = roc_auc_score(y_test, y_pred_proba)

        # Append the AU-ROC score to the array
        au_roc_scores.append(au_roc_score)

# Calculate the average AU-ROC score over all repetitions and folds
average_au_roc_score = sum(au_roc_scores) / len(au_roc_scores)

# Print the average AU-ROC score
print(f'Average AU-ROC Score: {average_au_roc_score}')

Average AU-ROC Score: 0.7930509554337103