In [ ]:
#we just do it once
#!pip3 install xgboost

In [4]:
from xgboost import XGBClassifier
import numpy as np
import pandas as pd
from pathlib import Path
import functools

In [2]:
# read data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)
# create model instance
bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
# fit model
bst.fit(X_train, y_train)
# make predictions

In [ ]:
preds = bst.predict(X_test)

In [ ]:
preds

In [ ]:
data['data'].shape

In [ ]:
data['data']

In [ ]:
 data['target']

In [ ]:
 data['target'].shape

In [3]:
#loading the data

path1=Path("/home/znazari/machine_learning_ppmi")

data_rna1=pd.read_csv(path1/"ordered_bl_matrix_ir2_count.txt", header=None,index_col=[0] )
data_rna=data_rna1.rename(columns=data_rna1.iloc[0]).drop(data_rna1.index[0]).reset_index(drop=True)

In [5]:
#loading the data quant

path1=Path("/home/znazari/machine_learning_ppmi")

quant_rna1=pd.read_csv(path1/"ordered_bl_matrix_ir2_quant.txt", header=None,index_col=[0] )
quant_rna=data_rna1.rename(columns=quant_rna1.iloc[0]).drop(quant_rna1.index[0]).reset_index(drop=True)

In [5]:
data_predict1=pd.read_csv(path1/"the_diagnosis_count_ir2.txt", header=None ,index_col=[0])
data_predict=data_predict1.rename(columns=data_predict1.iloc[0]).drop(data_predict1.index[0]).reset_index(drop=True)

In [6]:
#quant diagnosis prediction

quant_predict1=pd.read_csv(path1/"the_diagnosis_quant_ir2.txt", header=None ,index_col=[0])
quant_predict=quant_predict1.rename(columns=quant_predict1.iloc[0]).drop(quant_predict1.index[0]).reset_index(drop=True)

In [12]:
quant_rna

,Geneid,10874.0,12499.0,12593.0,13039.0,13424.0,14281.0,14331.0,14426.0,15761.0,...,59614.0,60002.0,60015.0,60024.0,60036.0,60095.0,60171.0,65002.0,65003.0,85242.0
0,ENSG00000223972.4,10,10,12,7,10,5,7,4,4,...,3,9,9,8,11,2,1,5,6,6
1,ENSG00000227232.4,192,418,276,252,292,235,162,209,128,...,348,158,205,210,512,211,134,168,235,432
2,ENSG00000243485.2,0,0,2,0,0,0,0,0,0,...,0,2,0,0,1,1,0,0,0,0
3,ENSG00000237613.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020.2,1,0,0,0,0,1,0,0,1,...,2,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57815,ENSG00000198695.2,346,142,169,158,138,241,65,83,493,...,258,136,69,86,132,59,142,50,93,92
57816,ENSG00000210194.1,48,17,28,24,24,54,3,7,85,...,46,25,10,16,13,12,13,5,16,4
57817,ENSG00000198727.2,766,1506,405,379,1316,581,501,328,517,...,966,461,498,1049,1260,494,402,147,872,2501
57818,ENSG00000210195.2,62,54,16,67,130,60,63,72,62,...,74,25,48,56,73,34,54,117,27,26
57819,ENSG00000210196.2,169,133,65,221,275,95,178,174,198,...,289,87,89,204,212,68,103,159,94,62

In [13]:
quant_rna_=quant_rna.drop(columns='Geneid')

In [16]:
a_quant_rna=quant_rna_.add(1)

In [19]:
log_quant_rna=np.log2(a_quant_rna)

In [20]:
d_log_quant_rna=pd.DataFrame(log_quant_rna)

In [22]:
# plus one and log2 transformed data of rna seq quant ir2
d_log_quant_rna

,10874.0,12499.0,12593.0,13039.0,13424.0,14281.0,14331.0,14426.0,15761.0,16580.0,...,59614.0,60002.0,60015.0,60024.0,60036.0,60095.0,60171.0,65002.0,65003.0,85242.0
0,3.459432,3.459432,3.700440,3.000000,3.459432,2.584963,3.000000,2.321928,2.321928,2.321928,...,2.000000,3.321928,3.321928,3.169925,3.584963,1.584963,1.000000,2.584963,2.807355,2.807355
1,7.592457,8.710806,8.113742,7.982994,8.194757,7.882643,7.348728,7.714246,7.011227,6.643856,...,8.447083,7.312883,7.686501,7.721099,9.002815,7.727920,7.076816,7.400879,7.882643,8.758223
2,0.000000,0.000000,1.584963,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.584963,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,1.584963,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57815,8.438792,7.159871,7.409391,7.312883,7.118941,7.918863,6.044394,6.392317,8.948367,6.129283,...,8.016808,7.098032,6.129283,6.442943,7.055282,5.906891,7.159871,5.672425,6.554589,6.539159
57816,5.614710,4.169925,4.857981,4.643856,4.643856,5.781360,2.000000,3.000000,6.426265,3.459432,...,5.554589,4.700440,3.459432,4.087463,3.807355,3.700440,3.807355,2.584963,4.087463,2.321928
57817,9.583083,10.557464,8.665336,8.569856,10.363040,9.184875,8.971544,8.361944,9.016808,7.592457,...,9.917372,8.851749,8.962896,10.036174,10.300353,8.951285,8.654636,7.209453,9.769838,11.288866
57818,5.977280,5.781360,4.087463,6.087463,7.033423,5.930737,6.000000,6.189825,5.977280,6.727920,...,6.228819,4.700440,5.614710,5.832890,6.209453,5.129283,5.781360,6.882643,4.807355,4.754888
57819,7.409391,7.066089,6.044394,7.794416,8.108524,6.584963,7.483816,7.451211,7.636625,6.820179,...,8.179909,6.459432,6.491853,7.679480,7.734710,6.108524,6.700440,7.321928,6.569856,5.977280

In [25]:
#transposed matrix
t_quant=d_log_quant_rna.T
t_quant

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
10874.0,3.459432,7.592457,0.000000,0.0,1.0,2.000000,0.0,5.285402,0.0,2.000000,...,9.932215,1.584963,1.0,3.169925,9.000000,8.438792,5.614710,9.583083,5.977280,7.409391
12499.0,3.459432,8.710806,0.000000,0.0,0.0,0.000000,0.0,6.087463,0.0,0.000000,...,10.623881,0.000000,0.0,0.000000,9.577429,7.159871,4.169925,10.557464,5.781360,7.066089
12593.0,3.700440,8.113742,1.584963,0.0,0.0,2.321928,2.0,6.554589,0.0,3.459432,...,8.569856,0.000000,0.0,1.000000,7.876517,7.409391,4.857981,8.665336,4.087463,6.044394
13039.0,3.000000,7.982994,0.000000,0.0,0.0,1.000000,0.0,5.087463,0.0,1.584963,...,8.784635,1.584963,0.0,1.000000,7.800900,7.312883,4.643856,8.569856,6.087463,7.794416
13424.0,3.459432,8.194757,0.000000,0.0,0.0,0.000000,0.0,5.781360,0.0,1.584963,...,10.559377,0.000000,1.0,1.584963,9.977280,7.118941,4.643856,10.363040,7.033423,8.108524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60095.0,1.584963,7.727920,1.000000,0.0,0.0,0.000000,0.0,5.857981,0.0,0.000000,...,8.909893,0.000000,1.0,0.000000,8.108524,5.906891,3.700440,8.951285,5.129283,6.108524
60171.0,1.000000,7.076816,0.000000,0.0,0.0,0.000000,0.0,2.807355,0.0,0.000000,...,8.891784,0.000000,0.0,1.000000,7.768184,7.159871,3.807355,8.654636,5.781360,6.700440
65002.0,2.584963,7.400879,0.000000,0.0,0.0,0.000000,0.0,4.392317,0.0,0.000000,...,7.076816,0.000000,0.0,0.000000,6.442943,5.672425,2.584963,7.209453,6.882643,7.321928
65003.0,2.807355,7.882643,0.000000,0.0,0.0,1.584963,1.0,6.169925,0.0,2.321928,...,9.938109,0.000000,0.0,0.000000,8.791163,6.554589,4.087463,9.769838,4.807355,6.569856
85242.0,2.807355,8.758223,0.000000,0.0,0.0,0.000000,0.0,7.149747,0.0,0.000000,...,11.086136,0.000000,2.0,1.000000,10.844706,6.539159,2.321928,11.288866,4.754888,5.977280

In [ ]:
data_rna_=data_rna.drop(columns='Geneid')

In [11]:
data_rna_1=data_rna_.T
data_rna_1

NameError: name 'data_rna_' is not defined

In [ ]:
data_predict_=data_predict['COHORT_DEFINITION']
data_predict_

In [26]:
searchfor = ['Healthy Control', "Parkinson's Disease"]

In [9]:
g=data_predict[data_predict['COHORT_DEFINITION'].astype(str).str.contains('|'.join(searchfor))]

In [27]:
quant_p=quant_predict[quant_predict['COHORT_DEFINITION'].astype(str).str.contains('|'.join(searchfor))]

In [28]:
quant_p

     BL_PATNO    COHORT_DEFINITION
0       10874  Parkinson's Disease
1       12499      Healthy Control
2       12593  Parkinson's Disease
3       13039  Parkinson's Disease
4       13424  Parkinson's Disease
...       ...                  ...
1114    58865  Parkinson's Disease
1116    59174  Parkinson's Disease
1119    60002  Parkinson's Disease
1124    60171  Parkinson's Disease
1127    85242  Parkinson's Disease

[773 rows x 2 columns]

In [13]:
patient_new=g['BL_PATNO']

In [29]:
quant_new_predict=quant_p['BL_PATNO']

In [17]:
r_new_patients=[int(x) for x in patient_new]

In [30]:
r_quant_patients=[int(x) for x in quant_new_predict]

In [31]:
r_quant_patients

[10874,
 12499,
 12593,
 13039,
 13424,
 14331,
 14426,
 16580,
 16785,
 17608,
 18567,
 3000,
 3001,
 3004,
 3008,
 3010,
 3011,
 3012,
 3013,
 3016,
 3020,
 3024,
 3026,
 3029,
 3050,
 3052,
 3053,
 3055,
 3058,
 3059,
 3062,
 3064,
 3068,
 3072,
 3073,
 3074,
 3075,
 3078,
 3082,
 3083,
 3089,
 3100,
 3104,
 3105,
 3106,
 3107,
 3108,
 3110,
 3118,
 3119,
 3123,
 3124,
 3125,
 3128,
 3130,
 3131,
 3132,
 3134,
 3150,
 3151,
 3156,
 3161,
 3162,
 3166,
 3168,
 3170,
 3174,
 3176,
 3179,
 3180,
 3181,
 3182,
 3183,
 3184,
 3185,
 3186,
 3188,
 3189,
 3190,
 3191,
 3200,
 3201,
 3203,
 3207,
 3211,
 3214,
 3216,
 3217,
 3218,
 3221,
 3225,
 3226,
 3227,
 3229,
 3230,
 3232,
 3233,
 3234,
 3237,
 3251,
 3252,
 3257,
 3262,
 3264,
 3268,
 3269,
 3272,
 3274,
 3276,
 3279,
 3280,
 3281,
 3284,
 3285,
 3300,
 3301,
 3305,
 3307,
 3308,
 3309,
 3310,
 3314,
 3316,
 3319,
 3320,
 3322,
 3323,
 3324,
 3326,
 3328,
 3332,
 3333,
 3350,
 3353,
 3355,
 3356,
 3357,
 3358,
 3362,
 3366,
 3367,
 3368,
 3372,
 3373,
 3374,
 3375,
 3376,
 3383,
 3385,
 3386,
 3387,
 3389,
 3392,
 3401,
 3402,
 3407,
 3408,
 3409,
 3410,
 3411,
 3413,
 3421,
 3424,
 3425,
 3426,
 3428,
 3430,
 3432,
 3433,
 3434,
 3440,
 3441,
 3442,
 3444,
 3445,
 3446,
 3447,
 3448,
 3450,
 3452,
 3453,
 3454,
 3455,
 3459,
 3460,
 3461,
 3462,
 3465,
 3467,
 3468,
 3472,
 3473,
 3476,
 3478,
 3479,
 3480,
 3501,
 3502,
 3503,
 3505,
 3510,
 3512,
 3517,
 3520,
 3521,
 3522,
 3525,
 3527,
 3528,
 3532,
 3536,
 3537,
 3538,
 3539,
 3544,
 3550,
 3558,
 3563,
 3564,
 3569,
 3570,
 3572,
 3573,
 3575,
 3582,
 3587,
 3601,
 3603,
 3605,
 3606,
 3607,
 3608,
 3609,
 3612,
 3614,
 3619,
 3620,
 3625,
 3628,
 3631,
 3635,
 3637,
 3638,
 3650,
 3651,
 3653,
 3654,
 3656,
 3658,
 3660,
 3661,
 3664,
 3665,
 3668,
 3701,
 3702,
 3707,
 3710,
 3711,
 3750,
 3751,
 3752,
 3753,
 3754,
 3755,
 3758,
 3760,
 3762,
 3763,
 3764,
 3765,
 3766,
 3767,
 3768,
 3770,
 3771,
 3772,
 3773,
 3775,
 3780,
 3781,
 3783,
 3784,
 3785,
 3788,
 3789,
 3792,
 3793,
 3794,
 3795,
 3796,
 3800,
 3803,
 3804,
 3805,
 3806,
 3807,
 3809,
 3810,
 3811,
 3812,
 3814,
 3817,
 3818,
 3819,
 3821,
 3823,
 3825,
 3827,
 3828,
 3830,
 3831,
 3832,
 3834,
 3835,
 3836,
 3850,
 3851,
 3852,
 3853,
 3854,
 3855,
 3856,
 3858,
 3859,
 3860,
 3862,
 3863,
 3865,
 3866,
 3868,
 3870,
 3871,
 3901,
 3905,
 3911,
 3914,
 3916,
 3917,
 3950,
 3951,
 3956,
 3957,
 3958,
 3960,
 3964,
 3967,
 3972,
 4004,
 4010,
 4011,
 4018,
 4020,
 4026,
 4027,
 4030,
 4032,
 4033,
 4034,
 40360,
 40366,
 4036,
 4038,
 40520,
 4053,
 4054,
 40553,
 4055,
 40560,
 4056,
 40578,
 40585,
 40586,
 4058,
 40590,
 40591,
 40593,
 40594,
 40595,
 40596,
 40599,
 4059,
 40603,
 40606,
 40607,
 40609,
 40610,
 40613,
 40614,
 40618,
 40621,
 4064,
 4066,
 40671,
 4067,
 4070,
 4073,
 4077,
 4078,
 40800,
 4080,
 4082,
 4085,
 4086,
 40882,
 4092,
 4093,
 4094,
 4096,
 4098,
 4099,
 4100,
 4101,
 4103,
 4104,
 4105,
 4106,
 4107,
 4109,
 4110,
 4111,
 4112,
 4113,
 4114,
 4116,
 4117,
 4118,
 4120,
 4121,
 4122,
 4124,
 4126,
 41280,
 41281,
 41282,
 41283,
 41285,
 41286,
 41287,
 41288,
 41289,
 41292,
 41293,
 41294,
 41295,
 41296,
 41305,
 41307,
 41356,
 4135,
 41382,
 41384,
 41399,
 41400,
 41410,
 41412,
 41420,
 41486,
 41508,
 41521,
 41522,
 41562,
 41578,
 41749,
 41767,
 41967,
 41992,
 41993,
 42001,
 42134,
 42172,
 42240,
 42306,
 42351,
 42429,
 42438,
 42443,
 42444,
 42450,
 42451,
 42454,
 42455,
 50044,
 50088,
 50110,
 50143,
 50172,
 50175,
 50184,
 50192,
 50195,
 50219,
 50222,
 50275,
 50319,
 50379,
 50485,
 50557,
 50572,
 50621,
 50670,
 50746,
 50860,
 50901,
 50961,
 51186,
 51392,
 51441,
 51518,
 51625,
 51755,
 51782,
 51867,
 51971,
 52128,
 52200,
 52276,
 52530,
 52787,
 52828,
 52872,
 52948,
 53113,
 53308,
 53595,
 53866,
 54048,
 54110,
 54156,
 54364,
 55151,
 55251,
 55395,
 55822,
 55842,
 56761,
 57447,
 57887,
 60003,
 60004,
 60006,
 60013,
 60023,
 60033,
 60035,
 60043,
 60044,
 60045,
 60057,
 60059,
 60065,
 60074,
 60075,
 60091,
 60096,
 60101,
 60108,
 60118,
 60122,
 65000,
 65004,
 65006,
 85236,
 90456,
 91097,
 91837,
 92490,
 92834,
 18026,
 18502,
 3006,
 3009,
 3018,
 3021,
 3025,
 3028,
 3051,
 3054,
 3061,
 3067,
 3071,
 3077,
 3080,
 3085,
 3102,
 3109,
 3111,
 3115,
 3116,
 3129,
 3154,
 3157,
 3172,
 3219,
 3224,
 3235,
 3253,
 3260,
 3270,
 3271,
 3311,
 3321,
 3330,
 3351,
 3352,
 3361,
 3364,
 3365,
 3377,
 3380,
 3381,
 3384,
 3390,
 3400,
 3403,
 3404,
 3406,
 3414,
 3417,
 3418,
 3419,
 3422,
 3423,
 3429,
 3451,
 3456,
 3457,
 3466,
 3470,
 3471,
 3475,
 3481,
 3482,
 3506,
 3507,
 3514,
 3518,
 3523,
 3540,
 3541,
 3542,
 3543,
 3557,
 3571,
 3585,
 3588,
 3593,
 3611,
 3613,
 3617,
 3630,
 3632,
 3634,
 3705,
 3757,
 3861,
 3908,
 3959,
 3961,
 3962,
 3970,
 4006,
 4022,
 4025,
 40273,
 4031,
 40558,
 40567,
 40568,
 40574,
 40616,
 40693,
 40702,
 40707,
 40714,
 40725,
 40726,
 4072,
 40730,
 40731,
 40735,
 40750,
 40754,
 40755,
 40757,
 40759,
 40760,
 40761,
 40763,
 40769,
 4076,
 40771,
 40772,
 40773,
 40776,
 40777,
 40778,
 40779,
 40784,
 40806,
 4084,
 4091,
 4108,
 4123,
 4125,
 41314,
 4136,
 41375,
 4139,
 41401,
 41430,
 41473,
 41513,
 41526,
 41568,
 41664,
 42006,
 42011,
 42014,
 42079,
 42128,
 42133,
 42146,
 42168,
 42263,
 42264,
 42346,
 42415,
 42447,
 42457,
 50028,
 50081,
 50157,
 50983,
 51440,
 51540,
 51544,
 51551,
 51557,
 51675,
 51731,
 51800,
 51914,
 52006,
 52414,
 52517,
 52518,
 52523,
 52524,
 52604,
 52678,
 52854,
 52871,
 52932,
 53033,
 53044,
 53054,
 53060,
 53310,
 53600,
 57961,
 57965,
 58027,
 58099,
 58138,
 58182,
 58224,
 58420,
 58865,
 59174,
 60002,
 60171,
 85242]

In [20]:
selected_data_rna=data_rna[r_new_patients]

In [33]:
#here we select those rna-seq data that includes both health control and parkinson 
selected_quant_rna=d_log_quant_rna[r_quant_patients]

In [34]:
select_quant_rna=selected_quant_rna.T

In [35]:
select_quant_rna

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
10874.0,3.459432,7.592457,0.000000,0.0,1.000000,2.000000,0.0,5.285402,0.0,2.000000,...,9.932215,1.584963,1.0,3.169925,9.000000,8.438792,5.614710,9.583083,5.977280,7.409391
12499.0,3.459432,8.710806,0.000000,0.0,0.000000,0.000000,0.0,6.087463,0.0,0.000000,...,10.623881,0.000000,0.0,0.000000,9.577429,7.159871,4.169925,10.557464,5.781360,7.066089
12593.0,3.700440,8.113742,1.584963,0.0,0.000000,2.321928,2.0,6.554589,0.0,3.459432,...,8.569856,0.000000,0.0,1.000000,7.876517,7.409391,4.857981,8.665336,4.087463,6.044394
13039.0,3.000000,7.982994,0.000000,0.0,0.000000,1.000000,0.0,5.087463,0.0,1.584963,...,8.784635,1.584963,0.0,1.000000,7.800900,7.312883,4.643856,8.569856,6.087463,7.794416
13424.0,3.459432,8.194757,0.000000,0.0,0.000000,0.000000,0.0,5.781360,0.0,1.584963,...,10.559377,0.000000,1.0,1.584963,9.977280,7.118941,4.643856,10.363040,7.033423,8.108524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58865.0,1.584963,7.800900,0.000000,0.0,0.000000,0.000000,0.0,5.169925,0.0,2.000000,...,8.636625,0.000000,0.0,0.000000,8.011227,6.409391,3.700440,8.807355,5.247928,6.807355
59174.0,2.000000,8.731319,0.000000,0.0,1.584963,0.000000,1.0,5.087463,0.0,1.000000,...,9.036174,0.000000,0.0,1.000000,8.430453,7.754888,4.857981,8.800900,5.906891,7.658211
60002.0,3.321928,7.312883,1.584963,0.0,0.000000,1.000000,0.0,6.832890,0.0,1.584963,...,9.095397,0.000000,0.0,1.000000,7.894818,7.098032,4.700440,8.851749,4.700440,6.459432
60171.0,1.000000,7.076816,0.000000,0.0,0.000000,0.000000,0.0,2.807355,0.0,0.000000,...,8.891784,0.000000,0.0,1.000000,7.768184,7.159871,3.807355,8.654636,5.781360,6.700440
85242.0,2.807355,8.758223,0.000000,0.0,0.000000,0.000000,0.0,7.149747,0.0,0.000000,...,11.086136,0.000000,2.0,1.000000,10.844706,6.539159,2.321928,11.288866,4.754888,5.977280

In [ ]:
data_predict['COHORT_DEFINITION'].replace(['Healthy Control', 'Prodromal','SWEDD',"Parkinson's Disease"],
                        [0, 1,2,3], inplace=True)

In [22]:
g['COHORT_DEFINITION'].replace(['Healthy Control', "Parkinson's Disease"],
                        [0, 1], inplace=True)

/tmp/ipykernel_7754/617596842.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['COHORT_DEFINITION'].replace(['Healthy Control', "Parkinson's Disease"],

In [36]:
quant_p['COHORT_DEFINITION'].replace(['Healthy Control', "Parkinson's Disease"],
                        [0, 1], inplace=True)

/tmp/ipykernel_27521/93247712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quant_p['COHORT_DEFINITION'].replace(['Healthy Control', "Parkinson's Disease"],

In [37]:
quant_p

     BL_PATNO  COHORT_DEFINITION
0       10874                  1
1       12499                  0
2       12593                  1
3       13039                  1
4       13424                  1
...       ...                ...
1114    58865                  1
1116    59174                  1
1119    60002                  1
1124    60171                  1
1127    85242                  1

[773 rows x 2 columns]

In [ ]:
data1_pred=data_predict['COHORT_DEFINITION']
data1_pred

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(data_rna_1,data1_pred, test_size=.3)

In [25]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(select_data_rna,g['COHORT_DEFINITION'], test_size=.3)

In [39]:
#here we split the data quant
X_trainq, X_testq, y_trainq, y_testq = train_test_split(select_quant_rna,quant_p['COHORT_DEFINITION'], test_size=.3)

In [45]:
X_trainq

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
40273.0,2.584963,7.768184,0.0,0.0,0.000000,0.0,0.0,3.906891,0.0,0.000000,...,9.677720,1.584963,1.000000,0.000000,8.654636,5.807355,2.584963,9.303781,6.507795,6.977280
3441.0,0.000000,8.330917,0.0,0.0,0.000000,0.0,0.0,5.426265,0.0,1.000000,...,10.292322,1.000000,0.000000,0.000000,9.157347,6.022368,3.169925,9.952741,5.700440,7.357552
41281.0,2.000000,8.527477,1.0,0.0,0.000000,0.0,0.0,6.129283,0.0,1.000000,...,9.936638,1.584963,1.584963,1.584963,9.057992,7.330917,5.044394,9.802516,5.129283,7.960002
3109.0,3.169925,6.643856,0.0,0.0,0.000000,0.0,0.0,5.554589,0.0,0.000000,...,9.556506,0.000000,0.000000,0.000000,8.447083,6.629357,3.584963,9.339850,5.459432,6.672425
3200.0,1.000000,7.507795,0.0,0.0,0.000000,0.0,0.0,5.209453,0.0,0.000000,...,9.008429,0.000000,1.000000,0.000000,8.417853,6.129283,3.700440,9.292322,5.491853,6.820179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42172.0,1.000000,6.442943,0.0,0.0,0.000000,0.0,0.0,5.247928,0.0,0.000000,...,9.721099,1.584963,0.000000,0.000000,8.864186,6.285402,4.247928,9.661778,4.087463,7.000000
3710.0,2.321928,8.479780,0.0,0.0,0.000000,0.0,0.0,7.033423,0.0,1.000000,...,10.590587,1.000000,0.000000,1.000000,9.529431,7.426265,4.169925,10.290019,5.614710,7.721099
3224.0,2.584963,6.988685,0.0,0.0,0.000000,0.0,0.0,4.700440,0.0,1.000000,...,8.573647,0.000000,1.000000,0.000000,7.523562,6.129283,3.000000,8.581201,4.954196,6.247928
3131.0,3.906891,7.467606,1.0,0.0,2.584963,3.0,0.0,5.882643,0.0,4.643856,...,9.543032,0.000000,0.000000,1.000000,8.741467,8.511753,5.754888,9.344296,4.584963,6.339850
3010.0,2.584963,7.839204,0.0,0.0,0.000000,0.0,0.0,4.643856,0.0,0.000000,...,7.794416,0.000000,0.000000,0.000000,6.894818,7.179909,4.247928,7.348728,5.727920,7.592457

In [46]:
X_testq

,0,1,2,3,4,5,6,7,8,9,...,57810,57811,57812,57813,57814,57815,57816,57817,57818,57819
52517.0,3.459432,6.988685,0.0,0.0,0.0,0.0,0.0,4.321928,0.0,0.000000,...,8.566054,0.000000,0.000000,0.000000,8.149747,6.303781,1.000000,8.554589,5.321928,6.000000
3557.0,1.584963,7.011227,0.0,0.0,0.0,0.0,0.0,6.285402,0.0,0.000000,...,8.885696,1.000000,0.000000,0.000000,8.169925,5.954196,3.700440,9.296916,5.459432,5.807355
40574.0,2.321928,7.219169,0.0,0.0,0.0,0.0,0.0,1.584963,0.0,2.000000,...,7.960002,0.000000,1.584963,1.584963,7.599913,7.515700,5.285402,8.252665,5.954196,8.055282
3462.0,3.000000,7.707359,0.0,0.0,0.0,1.0,0.0,5.584963,0.0,1.000000,...,8.823367,2.000000,0.000000,1.584963,7.960002,7.800900,5.426265,8.603626,5.584963,7.499846
3863.0,3.906891,8.778077,0.0,0.0,0.0,0.0,0.0,7.383704,0.0,1.000000,...,11.894439,1.584963,0.000000,1.584963,11.339293,8.076816,5.129283,11.501340,6.614710,8.771489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3386.0,1.584963,8.154818,0.0,0.0,0.0,0.0,0.0,4.392317,0.0,1.000000,...,9.063395,0.000000,0.000000,2.000000,8.228819,8.483816,5.285402,9.159871,6.768184,8.016808
3123.0,1.584963,8.076816,0.0,0.0,0.0,0.0,0.0,5.357552,0.0,2.321928,...,9.881114,2.000000,2.000000,2.584963,9.179909,9.733015,6.977280,9.710806,6.857981,7.727920
3421.0,3.000000,8.005625,0.0,0.0,0.0,0.0,0.0,5.459432,0.0,0.000000,...,8.945444,1.584963,0.000000,0.000000,7.569856,6.339850,3.169925,8.651052,5.554589,6.169925
3150.0,2.584963,8.599913,0.0,0.0,0.0,0.0,0.0,5.643856,0.0,1.584963,...,10.184875,2.000000,0.000000,0.000000,8.891784,7.531381,4.321928,9.850187,4.857981,7.348728
50746.0,3.700440,8.909893,0.0,0.0,0.0,0.0,0.0,5.247928,0.0,0.000000,...,11.122828,2.584963,1.000000,0.000000,9.894818,6.906891,4.754888,10.944712,5.727920,8.087463

In [47]:
y_trainq

852    1
197    0
519    1
710    1
96     1
      ..
565    1
300    1
733    1
69     1
19     1
Name: COHORT_DEFINITION, Length: 541, dtype: int64

In [ ]:
bst1 = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='reg:logistic')

In [40]:
bstq = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='reg:logistic')

In [26]:
bst3_hpa = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')

In [41]:
#here we make the model
bst_q = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')

In [ ]:
bst2 = XGBClassifier()

In [60]:
#let's see the free model 
xgb_classifier = XGBClassifier()

In [ ]:
bst1.fit(X_train1, y_train1)

In [61]:
#let's see the fit

xgb_classifier.fit(X_trainq, y_trainq)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [42]:
#here we fit the model
bst_q.fit(X_trainq, y_trainq)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
bst2.fit(X_train1, y_train1)

In [27]:
bst3_hpa.fit(X_train2, y_train2)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
preds1 = bst1.predict(X_test1)

In [43]:
#here we chech the prediction
preds_q = bst_q.predict(X_testq)

In [62]:
#let us see  the prediction!
preds_xgboost = xgb_classifier.predict(X_testq)

In [ ]:
preds2 = bst2.predic(X_test1)

In [29]:
preds3 = bst3_hpa.predict(X_test2)

In [ ]:
preds1

In [ ]:
X_test1

In [ ]:
#predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test1, preds1)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [30]:
#predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test2, preds3)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 67.24%

In [52]:
#let us see how the quant normalized data is doing
#predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_testq, preds_q)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 68.97%

In [63]:
#let us see the result!!
accuracyxgb = accuracy_score(y_testq, preds_xgboost)
print("Accuracy: %.2f%%" % (accuracyxgb * 100.0))

Accuracy: 75.00%

In [57]:
type(y_testq.values)

numpy.ndarray

In [58]:
type(preds_q)

numpy.ndarray

In [ ]:
#confusion matrix



#prediction 

print('Prediction : ',bst_q.predict(X_testq)
print('Groud truth: ',testv['target'].iloc[0])

print('\nPrediction probability')
print('Probability(0): ',clf_lr_w.predict_proba(testv.head(1))[0][0])
print('Probability(1): ',clf_lr_w.predict_proba(testv.head(1))[0][1])